"""followers

Revision ID: 535eba7f8eda
Revises: 965684dafa68
Create Date: 2018-11-25 20:33:04.727887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535eba7f8eda'
down_revision = '965684dafa68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
