"""new fields in user model

Revision ID: 965684dafa68
Revises: c325e13ab0c3
Create Date: 2018-11-24 13:52:44.656951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965684dafa68'
down_revision = 'c325e13ab0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
